site_name: Tian 文档

theme:
  name: material
  language: zh
  favicon: assets/img/logo.png
  logo: assets/img/logo.png
  palette:
    scheme: mk-ore
  font:
    text: Roboto
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
    - 首页: index.md
    - 开始游玩: start.md
    - 活动日历: announcement.md
    - 常见问题: help.md
copyright: Tian brid-geo
extra:
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
# Repository
repo_url: https://github.com/xiaoioi/TcsCraftdocs

extra_css:
  - assets/css/mk-ore/main.css