site_name: TcsCraft 文档
theme:
  name: material
  language: zh
  palette:
    primary: amber
nav:
    - 首页: index.md
    - 开始游玩: start.md
    - 常见问题: help.md
    - 论坛: https://www.xiqo.eu.org/
copyright: Copyright &copy; 2021 - 2022 xiaoioi
extra:
  generator: false
# Repository
repo_url: https://github.com/xiaoioi/TcsCraftdocs
