site_name: Tian 文档
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
    - 首页: index.md
    - 开始游玩: start.md
    - 活动日历: announcement.md
    - 常见问题: help.md
copyright: Copyright &copy; 2021 - 2022 xiaoioi mkdocs
extra:
  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
# Repository
repo_url: https://github.com/xiaoioi/TcsCraftdocs
